[book]
authors = ["baka4n"]
language = "en"
multilingual = true
shared-locale-resources = ["locales/core.flt"]
src = "src"
title = "{{fluent \"book-title\"}}"


[rust]
edition = "2018"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2