name: build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist_credentials: false
      - name: Build
        run: |
          git subtree push --prefix dist origin main